version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com focal main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update && apt-get install -y terraform=1.10.3-*

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - |
        terraform init
          -backend-config="bucket=${TFSTATE_BUCKET}"
          -backend-config="region=${AWS_REGION}"

  build:
    commands:
      - echo "Applying Terraform"
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
