version: 0.2

phases:
  pre_build:
    commands:
      - cd infra
      - echo "Initializing Terraform"
      - |
        terraform init \
          -backend-config="bucket=${TFSTATE_BUCKET}" \
          -backend-config="region=${AWS_REGION}"

  build:
    commands:
      - echo "Applying Terraform"
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
