version: 0.2

phases:
  pre_build:
    commands:
      - ls -la infra/script/pre_build.sh
      - infra/script/pre_build.sh

  build:
    commands:
      - infra/script/build.sh

artifacts:
  files:
    - '**/*'
