services:
  back-dev:
    build:
      context: ../back
      target: vscode-devcontainer
      args:
          - USER_ID=1000
          - GROUP_ID=1000
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:cached
    environment:
      REDIS_ENDPOINT: "task-db:6379"
    command: ["tail", "-f", "/dev/null"]
    restart: always
    depends_on:
      - task-db

  front-dev:
    build:
      context: ../front
      target: vscode-devcontainer
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:cached
    command: ["tail", "-f", "/dev/null"]
    restart: always

  task-db:
    image: redis
    restart: always
    